name: CI
on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: use node
      uses: actions/setup-node@v2
      with:
        node-version: 14 # node版本
    # react项目为npm run-script build，vue项目改为npm run build
    - name: Install and Build
      run: |
        npm install
        npm run build
     
    # react项目的FOLDER为build，vue项目改为dist   
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.CI }}
        BRANCH: gh-pages
        FOLDER: /dist
